/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_social_free(a: number): void;
export function __wbg_get_social_code(a: number, b: number): void;
export function __wbg_set_social_code(a: number, b: number, c: number): void;
export function __wbg_get_social_link(a: number, b: number): void;
export function __wbg_set_social_link(a: number, b: number, c: number): void;
export function __wbg_artist_free(a: number): void;
export function __wbg_get_artist_flag(a: number, b: number): void;
export function __wbg_set_artist_flag(a: number, b: number, c: number): void;
export function __wbg_get_artist_avatar(a: number, b: number): void;
export function __wbg_set_artist_avatar(a: number, b: number, c: number): void;
export function __wbg_get_artist_name(a: number, b: number): void;
export function __wbg_set_artist_name(a: number, b: number, c: number): void;
export function __wbg_get_artist_alias(a: number, b: number): void;
export function __wbg_set_artist_alias(a: number, b: number, c: number): void;
export function __wbg_get_artist_socials(a: number, b: number): void;
export function __wbg_set_artist_socials(a: number, b: number, c: number): void;
export function artist_to_bitcode(a: number, b: number): void;
export function artist_from_bitcode(a: number, b: number): number;
export function get_alias(a: number, b: number, c: number): void;
export function is_special(a: number, b: number): number;
export function __wbg_set_social_name(a: number, b: number, c: number): void;
export function __wbg_set_social_desc(a: number, b: number, c: number): void;
export function __wbg_get_social_name(a: number, b: number): void;
export function __wbg_get_social_desc(a: number, b: number): void;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_2(a: number, b: number, c: number): void;
